"""empty message

Revision ID: 69d4063ee6d1
Revises: 
Create Date: 2018-07-27 11:29:35.374517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d4063ee6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('phone', sa.String(length=10), nullable=True))
    op.drop_index('ix_organizations_name', table_name='organizations')
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.drop_index('ix_organizations_address', table_name='organizations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_organizations_address', 'organizations', ['address'], unique=1)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.create_index('ix_organizations_name', 'organizations', ['name'], unique=1)
    op.drop_column('organizations', 'phone')
    # ### end Alembic commands ###
