# coding: utf-8

"""
    Sawtooth REST API

    _This HTTP pragmatic REST API is built on top of Sawtooth's existing ZMQ/Protobuf infrastructure, simplifying client interaction with the blockchain by exposing endpoints that use common HTTP/JSON standards._   # noqa: E501

    OpenAPI spec version: 0.8.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BatchHeader(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'signer_public_key': 'str',
        'transaction_ids': 'list[str]'
    }

    attribute_map = {
        'signer_public_key': 'signer_public_key',
        'transaction_ids': 'transaction_ids'
    }

    def __init__(self, signer_public_key=None, transaction_ids=None):  # noqa: E501
        """BatchHeader - a model defined in Swagger"""  # noqa: E501

        self._signer_public_key = None
        self._transaction_ids = None
        self.discriminator = None

        if signer_public_key is not None:
            self.signer_public_key = signer_public_key
        if transaction_ids is not None:
            self.transaction_ids = transaction_ids

    @property
    def signer_public_key(self):
        """Gets the signer_public_key of this BatchHeader.  # noqa: E501


        :return: The signer_public_key of this BatchHeader.  # noqa: E501
        :rtype: str
        """
        return self._signer_public_key

    @signer_public_key.setter
    def signer_public_key(self, signer_public_key):
        """Sets the signer_public_key of this BatchHeader.


        :param signer_public_key: The signer_public_key of this BatchHeader.  # noqa: E501
        :type: str
        """

        self._signer_public_key = signer_public_key

    @property
    def transaction_ids(self):
        """Gets the transaction_ids of this BatchHeader.  # noqa: E501


        :return: The transaction_ids of this BatchHeader.  # noqa: E501
        :rtype: list[str]
        """
        return self._transaction_ids

    @transaction_ids.setter
    def transaction_ids(self, transaction_ids):
        """Sets the transaction_ids of this BatchHeader.


        :param transaction_ids: The transaction_ids of this BatchHeader.  # noqa: E501
        :type: list[str]
        """

        self._transaction_ids = transaction_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchHeader):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
